[project]
name = "minimal-rag-ingest"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "feedparser>=6.0.10",
  "httpx>=0.27.0",
  "python-dateutil>=2.9.0",
  "trafilatura>=1.9.0",
  "tqdm>=4.66.4",
  "beautifulsoup4>=4.12.2", 
  "playwright>=1.42.0"

]
